### PR TITLE
Use jest for tests

### PR DESCRIPTION
**Pull request by SimenB**
Also add package-lock.json and CI on node 8 (to get npm5)

Would anyone be opposed to me dropping gulp entirely and just use webpack directly from npm scripts?

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
This repo is your oyster. If no one complains. Feel free to take gulp out

**Review by codefromthecrypt — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
Thank you!

**Comment by SimenB** [comment]
Cool. The firefox add-on needs a rewrite as it'll stop working in firefox 57 (55 is current). The good thing is it uses the same API as chrome, opera and microsoft edge now, so should actually be less code and very straight forward 🙂 That also means that a fancy build system is unnecessary.

**Comment by codefromthecrypt** [comment]
you are such a champ for helping, Simen. Hope to see you in oslo if we can
meet. I'll be there soon for javazone!

**Comment by SimenB** [comment]
I'll be at javazone myself, so that works out!

**Comment by eirslett** [comment]
Go for it! Finally some cleanup on this project! I just wish firefox supported the same api back when this was written :-( Gulp was only there to manage the abstraction etc., so removing it is good.

**Pull request merged**
